# Copyright(c)  2026. Open Security Research, Inc. - All Rights Reserved

# Open Security Research, Inc. remains the sole owner of this source code copyrights,
# trademark and any applicable intellectual property.

import numpy as np
import nuscar
import nuscar.nuscar_rust as _n_rust

BLOCK_SIZE = 64
_INITIAL_HASH = [
    0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476, 0xC3D2E1F0
]
# SHA-1 round constants
_ROUND_K = [0x5A827999] * 20 + [0x6ED9EBA1] * 20 + [0x8F1BBCDC] * 20 + [0xCA62C1D6] * 20


def rotl(x, n):
    return ((x << n) | (x >> (32 - n))) & 0xFFFFFFFF


def uint32_to_uint8_array(value):
    """
    Convert a 32-bit integer to a 4-byte numpy uint8 array (big-endian).
    Supports scalar or array input.
    """
    if isinstance(value, (int, np.integer)):
        return np.array([
            (value >> 24) & 0xFF,
            (value >> 16) & 0xFF,
            (value >> 8) & 0xFF,
            value & 0xFF
        ], dtype=np.uint8)
    else:
        value = np.asarray(value, dtype=np.uint32)
        return np.stack([
            (value >> 24) & 0xFF,
            (value >> 16) & 0xFF,
            (value >> 8) & 0xFF,
            value & 0xFF
        ], axis=-1).astype(np.uint8)


def uint8_array_to_uint32(arr):
    """
    Convert a uint8 array to a 32-bit integer (big-endian).
    Supports 1D array of shape (4,) or 2D array of shape (N, 4).
    """
    arr = np.asarray(arr, dtype=np.uint8)
    if arr.ndim == 1:
        return (np.uint32(arr[0]) << 24) | (np.uint32(arr[1]) << 16) | \
               (np.uint32(arr[2]) << 8) | np.uint32(arr[3])
    else:
        return (arr[:, 0].astype(np.uint32) << 24) | \
               (arr[:, 1].astype(np.uint32) << 16) | \
               (arr[:, 2].astype(np.uint32) << 8) | \
               arr[:, 3].astype(np.uint32)


# SHA-1 logic functions
def ch(b, c, d):
    """Ch function: used in rounds 0-19"""
    return (b & c) | (~b & d)


def parity(b, c, d):
    """Parity function: used in rounds 20-39 and 60-79"""
    return b ^ c ^ d


def maj(b, c, d):
    """Maj function: used in rounds 40-59"""
    return (b & c) | (b & d) | (c & d)


def compute_padded_key(key: bytes, pad: int) -> bytes:
    """
    Compute the HMAC padded key.

    Args:
        key: original key, bytes type
        pad: padding byte value, 0x36 (ipad) or 0x5c (opad)
    Returns:
        padded and XORed key, length BLOCK_SIZE (64 bytes)
    """
    # If key length exceeds BLOCK_SIZE, hash it first
    if len(key) > BLOCK_SIZE:
        key = sha1(key)

    # Pad to BLOCK_SIZE
    if len(key) < BLOCK_SIZE:
        key = key + b'\x00' * (BLOCK_SIZE - len(key))

    # XOR with pad
    pad_bytes = bytes([pad] * BLOCK_SIZE)
    padded_key = bytes(k ^ p for k, p in zip(key, pad_bytes))
    return padded_key


def compute_hi_ho(padded_key: bytes) -> list:
    """Compute the initial hash values of HMAC-SHA1 inner/outer hash (after pad processing)"""
    return list(_n_rust.sha1_compute_hi_ho_r(list(padded_key)))


def compute_w(plaintext, w_index):
    """
    Compute the message word W[w_index] of HMAC-SHA1 inner hash.

    Args:
        plaintext: plaintext data, can be bytes or numpy uint8 array
        w_index: message word index (0-79)
    Returns:
        - If plaintext is bytes: returns a single 32-bit integer
        - If plaintext is 1D array: returns uint8 array of shape (4,)
        - If plaintext is 2D array: returns uint8 array of shape (N, 4)
    """
    if isinstance(plaintext, bytes):
        length_in_bits = (BLOCK_SIZE + len(plaintext)) * 8
        data = plaintext + b'\x80'
        while (len(data) * 8) % 512 != 448:
            data += b'\x00'
        data += length_in_bits.to_bytes(8, 'big')
        return sha1_expand_message(data)[w_index]

    # numpy array input
    plaintext = np.asarray(plaintext, dtype=np.uint8)
    if plaintext.ndim == 1:
        plaintext = plaintext[np.newaxis, :]
        result = _n_rust.sha1_compute_w_r(nuscar._global_pool, np.ascontiguousarray(plaintext), w_index)
        return result[0]
    elif plaintext.ndim == 2:
        plaintext = np.ascontiguousarray(plaintext, dtype=np.uint8)
        return _n_rust.sha1_compute_w_r(nuscar._global_pool, plaintext, w_index)


def compute_w0(plaintext):
    return compute_w(plaintext, 0)


def compute_w1(plaintext):
    return compute_w(plaintext, 1)


def compute_delta0(padded_key: bytes) -> np.ndarray:
    """
    Compute the delta0 value of HMAC-SHA1 (e + f(b,c,d) + K[0] + ROTL(a,5)).

    Args:
        padded_key: pad-processed key, bytes type, generated by compute_padded_key(key, 0x36)
    Returns:
        4-byte representation of delta0, numpy uint8 array, shape (4,), big-endian
    """
    a, b, c, d, e = compute_hi_ho(padded_key)
    delta0 = (e + ch(b, c, d) + _ROUND_K[0] + rotl(a, 5)) & 0xFFFFFFFF
    return uint32_to_uint8_array(delta0)


def compute_t0(plaintext: np.ndarray, delta0: np.ndarray):
    """
    Compute the temp value of the first round of the second block of HMAC-SHA1.
    temp = ROTL(a,5) + f(b,c,d) + e + K[0] + W[0]
         = delta0 + W[0]

    Args:
        plaintext: plaintext data, numpy uint8 array, shape (n, m) or (m,)
        delta0: delta0 value, numpy uint8 array, shape (4,) or (n, 4)
    Returns:
        temp0 as 32-bit integer
    """
    w0 = compute_w0(plaintext)
    delta0_val = uint8_array_to_uint32(delta0)
    w0_val = uint8_array_to_uint32(w0)
    return (delta0_val + w0_val) & 0xFFFFFFFF


def compute_t0_hw(plaintext: np.ndarray, delta0: np.ndarray):
    res = uint32_to_uint8_array(compute_t0(plaintext, delta0))
    return nuscar.leakmodel.leakage_model_hw(res, nb_words=1)


def compute_a0_to_e0(padded_key: bytes) -> dict:
    """
    Compute all state values a0 to e0 after compressing the first block (ipad) of HMAC-SHA1.

    Args:
        padded_key: pad-processed key, bytes type, generated by compute_padded_key(key, 0x36)
    Returns:
        dict containing a0 to e0, each value is a numpy uint8 array, shape (4,), big-endian
    """
    a0, b0, c0, d0, e0 = compute_hi_ho(padded_key)
    return {
        'a0': uint32_to_uint8_array(a0),
        'b0': uint32_to_uint8_array(b0),
        'c0': uint32_to_uint8_array(c0),
        'd0': uint32_to_uint8_array(d0),
        'e0': uint32_to_uint8_array(e0)
    }


def attack_delta0_hw(plaintext: np.ndarray, byte_index: int,
                     known_bytes=None, guesses=np.arange(256, dtype=np.uint8)):
    """
    Attack a specific byte of delta0.
    Compute the Hamming weight of the target byte of temp0 = delta0 + W[0]
    using known W[0] and guessed delta0 bytes.

    Args:
        plaintext: array of shape (N, ...)
        byte_index: byte index to attack (0=MSB, 3=LSB)
        known_bytes: list of known lower bytes, ordered from LSB to MSB
        guesses: guess value array, default 0-255
    Returns:
        Hamming weight array of shape (N, 256, 1)
    """
    plaintext = np.asarray(plaintext, dtype=np.uint8)
    if plaintext.ndim == 1:
        plaintext = plaintext[np.newaxis, :]
    return _n_rust.sha1_attack_delta0_hw_r(
        nuscar._global_pool, plaintext, byte_index,
        list(guesses),
        list(known_bytes) if known_bytes is not None else None
    )


def compute_r1(padded_key: bytes) -> np.ndarray:
    """
    Compute R1 = Ch(a0, ROTL(b0,30), c0) + d0 + K[1]

    Args:
        padded_key: pad-processed key
    Returns:
        4-byte representation of R1, numpy uint8 array, shape (4,)
    """
    a0, b0, c0, d0, e0 = compute_hi_ho(padded_key)
    b0_rot30 = rotl(b0, 30)
    r1 = (ch(a0, b0_rot30, c0) + d0 + _ROUND_K[1]) & 0xFFFFFFFF
    return uint32_to_uint8_array(r1)


def compute_t1(plaintext: np.ndarray, delta0: np.ndarray, r1: np.ndarray):
    """
    Compute the temp value of the second round.
    T1 = ROTL(T0,5) + R1 + W[1]
       = ROTL(delta0 + W[0], 5) + R1 + W[1]

    Args:
        plaintext: plaintext data
        delta0: delta0 value, numpy uint8 array
        r1: R1 value, numpy uint8 array
    Returns:
        T1 as 32-bit integer
    """
    w0 = compute_w0(plaintext)
    w1 = compute_w1(plaintext)
    w0_val = uint8_array_to_uint32(w0)
    w1_val = uint8_array_to_uint32(w1)
    delta0_val = uint8_array_to_uint32(delta0)
    r1_val = uint8_array_to_uint32(r1)
    t0 = (delta0_val + w0_val) & 0xFFFFFFFF
    t1 = (rotl(t0, 5) + r1_val + w1_val) & 0xFFFFFFFF
    return t1


def compute_t1_hw(plaintext: np.ndarray, delta0: np.ndarray, r1: np.ndarray):
    res = uint32_to_uint8_array(compute_t1(plaintext, delta0, r1))
    return nuscar.leakmodel.leakage_model_hw(res, nb_words=1)


def attack_r1_hw(plaintext: np.ndarray, delta0: np.ndarray, byte_index: int,
                 known_bytes=None, guesses=np.arange(256, dtype=np.uint8)):
    """
    Attack a specific byte of R1 (DPA 2).
    R1 = Ch(a0, ROTL(b0,30), c0) + d0 + K[1]
    T1 = ROTL(T0,5) + R1 + W[1]
    Recover R1 by observing T1 leakage with known T0 and W[1].

    Args:
        plaintext: array of shape (N, ...)
        delta0: recovered delta0 value, numpy uint8 array, shape (4,)
        byte_index: byte index to attack (0=MSB, 3=LSB)
        known_bytes: list of known lower bytes
        guesses: guess value array
    Returns:
        Hamming weight array of shape (N, 256, 1)
    """
    plaintext = np.asarray(plaintext, dtype=np.uint8)
    if plaintext.ndim == 1:
        plaintext = plaintext[np.newaxis, :]
    return _n_rust.sha1_attack_r1_hw_r(
        nuscar._global_pool, plaintext, delta0, byte_index,
        list(guesses),
        list(known_bytes) if known_bytes is not None else None
    )


def compute_ch_f3(plaintext: np.ndarray, delta0: np.ndarray, r1: np.ndarray,
                   a0_rot30: np.ndarray):
    """
    Compute the Ch function output F3 of round 4.
    F3 = Ch(T1, ROTL(T0, 30), ROTL(a0, 30))

    Args:
        plaintext: plaintext data
        delta0: delta0 value
        r1: R1 value
        a0_rot30: ROTL(a0, 30) value
    Returns:
        F3 as 32-bit integer
    """
    w0 = compute_w0(plaintext)
    w1 = compute_w1(plaintext)

    w0_val = uint8_array_to_uint32(w0)
    w1_val = uint8_array_to_uint32(w1)
    delta0_val = uint8_array_to_uint32(delta0)
    r1_val = uint8_array_to_uint32(r1)
    a0_rot30_val = uint8_array_to_uint32(a0_rot30)

    # Compute T0 and T1
    t0 = (delta0_val + w0_val) & 0xFFFFFFFF
    t1 = (rotl(t0, 5) + r1_val + w1_val) & 0xFFFFFFFF

    # Compute ROTL(T0, 30)
    t0_rot30 = rotl(t0, 30)

    # Compute Ch(T1, ROTL(T0, 30), ROTL(a0, 30))
    # Note: round 4 (i=3) is still in range 0-19, uses Ch function
    f3 = ch(t1, t0_rot30, a0_rot30_val)

    return f3


def compute_ch_f3_hw(plaintext: np.ndarray, delta0: np.ndarray, r1: np.ndarray,
                   a0_rot30: np.ndarray):
    res = compute_ch_f3(plaintext, delta0, r1, a0_rot30)
    return nuscar.leakmodel.leakage_model_hw(uint32_to_uint8_array(res), nb_words=1)


def attack_a0_rot30_hw(plaintext: np.ndarray, delta0: np.ndarray, r1: np.ndarray,
                        guesses=np.arange(256, dtype=np.uint8)):
    """
    Attack ROTL(a0, 30) by observing round 4 Ch function output F3 = Ch(T1, ROTL(T0, 30), ROTL(a0, 30)).
    With known T1 and ROTL(T0, 30), observe F3 leakage to recover ROTL(a0, 30).
    F3 = (T1 & ROTL(T0,30)) ^ (~T1 & ROTL(a0,30))

    Args:
        plaintext: array of shape (N, ...)
        delta0: recovered delta0 value
        r1: recovered R1 value
        guesses: guess value array
    Returns:
        Hamming weight array of shape (N, 256, 4),
        corresponding to the 4 bytes of ROTL(a0,30)
    """
    plaintext = np.asarray(plaintext, dtype=np.uint8)
    if plaintext.ndim == 1:
        plaintext = plaintext[np.newaxis, :]
    return _n_rust.sha1_attack_a0_rot30_hw_r(
        nuscar._global_pool, plaintext, delta0, r1, list(guesses)
    )


def compute_ch_f2(plaintext: np.ndarray, delta0: np.ndarray, r1: np.ndarray,
                   a0_rot30: np.ndarray, b0_rot30: np.ndarray):
    """
    Compute the Ch function output F2 of round 3.
    F2 = Ch(T0, ROTL(a0, 30), ROTL(b0, 30))

    Args:
        plaintext: plaintext data
        delta0: delta0 value
        r1: R1 value
        a0_rot30: ROTL(a0, 30) value
        b0_rot30: ROTL(b0, 30) value
    Returns:
        F2 as 32-bit integer
    """
    w0 = compute_w0(plaintext)
    w0_val = uint8_array_to_uint32(w0)
    delta0_val = uint8_array_to_uint32(delta0)
    a0_rot30_val = uint8_array_to_uint32(a0_rot30)
    b0_rot30_val = uint8_array_to_uint32(b0_rot30)

    # Compute T0
    t0 = (delta0_val + w0_val) & 0xFFFFFFFF

    # Compute Ch(T0, ROTL(a0, 30), ROTL(b0, 30))
    # Note: round 3 (i=2) is still in range 0-19, uses Ch function
    f2 = ch(t0, a0_rot30_val, b0_rot30_val)

    return f2


def compute_ch_f2_hw(plaintext: np.ndarray, delta0: np.ndarray, r1: np.ndarray,
                   a0_rot30: np.ndarray, b0_rot30: np.ndarray):
    res = compute_ch_f2(plaintext, delta0, r1, a0_rot30, b0_rot30)
    return nuscar.leakmodel.leakage_model_hw(uint32_to_uint8_array(res), nb_words=1)


def attack_b0_rot30_hw(plaintext: np.ndarray, delta0: np.ndarray, a0_rot30: np.ndarray,
                        guesses=np.arange(256, dtype=np.uint8)):
    """
    Attack ROTL(b0, 30) by observing round 3 Ch function output F2 = Ch(T0, ROTL(a0, 30), ROTL(b0, 30)).
    With known T0 and ROTL(a0, 30), observe F2 leakage to recover ROTL(b0, 30).
    F2 = (T0 & ROTL(a0,30)) ^ (~T0 & ROTL(b0,30))

    Args:
        plaintext: array of shape (N, ...)
        delta0: recovered delta0 value
        a0_rot30: recovered ROTL(a0,30) value
        guesses: guess value array
    Returns:
        Hamming weight array of shape (N, 256, 4), attacking all 4 bytes simultaneously
    """
    plaintext = np.asarray(plaintext, dtype=np.uint8)
    if plaintext.ndim == 1:
        plaintext = plaintext[np.newaxis, :]
    return _n_rust.sha1_attack_b0_rot30_hw_r(
        nuscar._global_pool, plaintext, delta0, a0_rot30, list(guesses)
    )


def compute_t2(plaintext: np.ndarray, delta0: np.ndarray, r1: np.ndarray,
               a0_rot30: np.ndarray, b0_rot30: np.ndarray, c0: np.ndarray):
    """
    Compute the temp value of round 3.
    T2 = ROTL(T1,5) + Ch(T0, ROTL(a0,30), ROTL(b0,30)) + c0 + K[2] + W[2]

    Args:
        plaintext: plaintext data
        delta0: delta0 value
        r1: R1 value
        a0_rot30: ROTL(a0,30) value
        b0_rot30: ROTL(b0,30) value
        c0: c0 value
    Returns:
        T2 as 32-bit integer
    """
    w0 = compute_w0(plaintext)
    w1 = compute_w1(plaintext)
    w2 = compute_w(plaintext, 2)

    w0_val = uint8_array_to_uint32(w0)
    w1_val = uint8_array_to_uint32(w1)
    w2_val = uint8_array_to_uint32(w2)
    delta0_val = uint8_array_to_uint32(delta0)
    r1_val = uint8_array_to_uint32(r1)
    a0_rot30_val = uint8_array_to_uint32(a0_rot30)
    b0_rot30_val = uint8_array_to_uint32(b0_rot30)
    c0_val = uint8_array_to_uint32(c0)

    # Compute T0 and T1
    t0 = (delta0_val + w0_val) & 0xFFFFFFFF
    t1 = (rotl(t0, 5) + r1_val + w1_val) & 0xFFFFFFFF

    # Compute Ch(T0, ROTL(a0,30), ROTL(b0,30))
    # Note: round 3 (i=2) is still in range 0-19, uses Ch function
    ch_val = ch(t0, a0_rot30_val, b0_rot30_val)

    # Compute T2
    t2 = (rotl(t1, 5) + ch_val + c0_val + _ROUND_K[2] + w2_val) & 0xFFFFFFFF
    return t2


def compute_t2_hw(plaintext: np.ndarray, delta0: np.ndarray, r1: np.ndarray,
                 a0_rot30: np.ndarray, b0_rot30: np.ndarray, c0: np.ndarray):
    res = compute_t2(plaintext, delta0, r1, a0_rot30, b0_rot30, c0)
    return nuscar.leakmodel.leakage_model_hw(uint32_to_uint8_array(res), nb_words=1)


def attack_c0_hw(plaintext: np.ndarray, delta0: np.ndarray, r1: np.ndarray,
                 a0_rot30: np.ndarray, b0_rot30: np.ndarray, byte_index: int,
                 known_bytes=None, guesses=np.arange(256, dtype=np.uint8)):
    """
    Attack c0 (DPA 5).
    T2 = ROTL(T1,5) + Ch(T0, ROTL(a0,30), ROTL(b0,30)) + c0 + K[2] + W[2]

    With all other terms known, observe T2 leakage to recover c0.

    Args:
        plaintext: array of shape (N, ...)
        delta0: recovered delta0 value
        r1: recovered R1 value
        a0_rot30: recovered ROTL(a0,30) value
        b0_rot30: recovered ROTL(b0,30) value
        byte_index: byte index to attack (0=MSB, 3=LSB)
        known_bytes: list of known lower bytes
        guesses: guess value array
    Returns:
        Hamming weight array of shape (N, 256, 1)
    """
    plaintext = np.asarray(plaintext, dtype=np.uint8)
    if plaintext.ndim == 1:
        plaintext = plaintext[np.newaxis, :]
    return _n_rust.sha1_attack_c0_hw_r(
        nuscar._global_pool, plaintext, delta0, r1, a0_rot30, b0_rot30, byte_index,
        list(guesses),
        list(known_bytes) if known_bytes is not None else None
    )


def rotr(x, n):
    """Right rotate by n bits"""
    return ((x >> n) | (x << (32 - n))) & 0xFFFFFFFF


def recover_sha1_state(r0: np.ndarray, r1: np.ndarray, a0_rot30: np.ndarray,
                       b0_rot30: np.ndarray, c0: np.ndarray) -> dict:
    # Recover original values from rotated values
    a0_rot30_32bit = int(uint8_array_to_uint32(a0_rot30))
    b0_rot30_32bit = int(uint8_array_to_uint32(b0_rot30))
    # ROTL(a0, 30) -> a0, i.e. ROTR(ROTL(a0,30), 30) = a0
    a0 = rotr(a0_rot30_32bit, 30)
    b0 = rotr(b0_rot30_32bit, 30)

    # c0 is already c0 itself (recovered c0 from attack)
    c0_32bit = int(uint8_array_to_uint32(c0))
    # Recover d0 from R1
    # R1 = Ch(a0, ROTL(b0,30), c0) + d0 + K[1]
    # d0 = R1 - Ch(a0, ROTL(b0,30), c0) - K[1]
    r1_32bit = int(uint8_array_to_uint32(r1))
    ch_a0_b0rot_c0 = ch(a0, b0_rot30_32bit, c0_32bit)
    d0 = (r1_32bit - ch_a0_b0rot_c0 - _ROUND_K[1]) & 0xFFFFFFFF

    # Recover e0 from R0
    # R0 = e0 + Ch(b0,c0,d0) + K[0] + ROTL(a0,5)
    # e0 = R0 - Ch(b0,c0,d0) - K[0] - ROTL(a0,5)
    r0_32bit = int(uint8_array_to_uint32(r0))
    ch_b0_c0_d0 = ch(b0, c0_32bit, d0)
    e0 = (r0_32bit - ch_b0_c0_d0 - _ROUND_K[0] - rotl(a0, 5)) & 0xFFFFFFFF

    return {
        'a0': uint32_to_uint8_array(a0),
        'b0': uint32_to_uint8_array(b0),
        'c0': uint32_to_uint8_array(c0_32bit),
        'd0': uint32_to_uint8_array(d0),
        'e0': uint32_to_uint8_array(e0)
    }


def sha1_expand_message(block: bytes) -> list:
    """
    Expand a 512-bit message block into a message schedule array of 80 32-bit words.

    Args:
        block: 64-byte message block (bytes).
    Returns:
        a list of 80 32-bit words (list).
    """
    return list(_n_rust.sha1_expand_message_r(list(block)))


def sha1(data, iv: list = None):
    """
    Args:
        data: data to hash, can be:
            - bytes: byte data
            - np.ndarray (uint8): 1D or 2D array
              - 1D: shape (n,), returns a single hash
              - 2D: shape (m, n), returns m hashes
        iv: optional initial vector, list of 5 32-bit integers. If provided, used for HMAC computation.
    Returns:
        - If input is bytes or 1D array: returns a 20-byte bytes object
        - If input is 2D array: returns numpy uint8 array of shape (m, 20)
    """
    if isinstance(data, np.ndarray):
        if data.ndim == 1:
            return bytes(_n_rust.sha1_hash_r(list(data.tobytes()), iv))
        elif data.ndim == 2:
            data = np.ascontiguousarray(data, dtype=np.uint8)
            return _n_rust.sha1_hash_batch_r(nuscar._global_pool, data, iv)
        else:
            raise ValueError("data array dimension must be 1 or 2")

    # bytes input
    return bytes(_n_rust.sha1_hash_r(list(data), iv))


def hmac(key: bytes, msg: bytes) -> bytes:
    """
    HMAC-SHA1 implementation per RFC 2104.

    Args:
        key: key for HMAC (bytes).
        msg: message to authenticate (bytes).

    Returns:
        a 20-byte bytes object representing the computed HMAC-SHA1 value.
    """
    return bytes(_n_rust.sha1_hmac_r(list(key), list(msg)))


# --- Verification ---
if __name__ == '__main__':
    import hashlib
    print("=== SHA-1 Verification ===")

    # Test case 1: empty string
    test_data = b""
    my_result = sha1(test_data)
    std_result = hashlib.sha1(test_data).digest()
    print(f"Empty string:")
    print(f"My impl:  {my_result.hex()}")
    print(f"Stdlib:   {std_result.hex()}")
    print(f"Match: {my_result == std_result}\n")

    # Test case 2: "abc"
    test_data = b"abc"
    my_result = sha1(test_data)
    std_result = hashlib.sha1(test_data).digest()
    print(f"'abc':")
    print(f"My impl:  {my_result.hex()}")
    print(f"Stdlib:   {std_result.hex()}")
    print(f"Match: {my_result == std_result}\n")


